### PR TITLE
Sort options keys when saving to file

### PR DESCRIPTION
**Pull request by zls0424**
avoid unnecessary .skeema file changes when checking into git

### CODE REVIEW

**Comment by evanelias** [comment]
Makes sense and looks good. Thank you for the pull request! I'll aim to merge in the next day or two.

Longer-term, the entire File.Write() method should probably be rewritten to preserve comments, whitespace, and whatever order the user previously used... but this is good for now 👍

Just to make sure I describe this change correctly in the eventual Skeema release notes, can you please give example(s) of which commands/situations were causing unnecessary reordering? (I am guessing perhaps when `skeema pull` detects changes to a server flavor or schema charset/collation? Any other situations too?) Thanks!

**Comment by zls0424** [comment]
Thanks for your reply and the great project.  Yeah, one example is when running `skeema pull` after schema charset/collation changes. Another one (and the one for us) is that we sometimes use `skeema init` instead of `skeema pull`. This is because we need the ability to `run pull/push/diff only on specific databases or tables`, so we use a script now, which runs `skeema init` in a clean directory and then copy the specific schema dir or table sql files from or to the right place. Maybe it would be better for skeema to support this ;-)

**Comment by evanelias** [comment]
> This is because we need the ability to run pull/push/diff only on specific databases or tables

Ah, makes sense, thanks! There are some existing Skeema features that may help with this:

* If you only want to pull/push/diff a specific *database*, `cd` to that database's subdirectory and run `skeema` from there. Skeema operates recursively from the working directory it is invoked from, so if you run it from a bottom-level subdir, it will just run against whatever database that subdir maps to. (Parent dir *option files* will still affect its behavior, though -- so if the parent dir's .skeema file defines the `host`, the option value will still be inherited by the subdir.)

* If there's any pattern to the database names and/or table names that you want to skip, you can use [--ignore-schema](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-schema) or [--ignore-table](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-table) ad-hoc on the command line.

Not sure if those help with your use-case though. Probably depends on what you're skipping and why :) I'd love to learn more about what would help most in your situation -- please [open an issue in skeema/skeema](https://github.com/skeema/skeema/issues/new) if you'd like. Thanks!

**Comment by evanelias** [comment]
This PR is now merged, and included in mybase v1.0.5. Thanks again!

Final step is to update the vendored dep of this package inside of skeema/skeema. I could do this on my end, or you can do it as a pull request on skeema/skeema; whichever you'd prefer is fine with me :)

If doing it as a pull request, you'll need the [golang/dep tool](https://github.com/golang/dep) tool to run the command `dep ensure -update github.com/skeema/mybase`. (I hope to switch away from `dep` to the newer Golang module support soon, but haven't quite yet.)

**Comment by zls0424** [comment]
> > This is because we need the ability to run pull/push/diff only on specific databases or tables
> 
> Ah, makes sense, thanks! There are some existing Skeema features that may help with this:
> 
> * If you only want to pull/push/diff a specific _database_, `cd` to that database's subdirectory and run `skeema` from there. Skeema operates recursively from the working directory it is invoked from, so if you run it from a bottom-level subdir, it will just run against whatever database that subdir maps to. (Parent dir _option files_ will still affect its behavior, though -- so if the parent dir's .skeema file defines the `host`, the option value will still be inherited by the subdir.)
> * If there's any pattern to the database names and/or table names that you want to skip, you can use [--ignore-schema](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-schema) or [--ignore-table](https://github.com/skeema/skeema/blob/master/doc/options.md#ignore-table) ad-hoc on the command line.
> 
> Not sure if those help with your use-case though. Probably depends on what you're skipping and why :) I'd love to learn more about what would help most in your situation -- please [open an issue in skeema/skeema](https://github.com/skeema/skeema/issues/new) if you'd like. Thanks!

I'll reconsider my use case and open the issue later, and about the two features, I did try them before my final script~ 
* `cd` to the _database_ directory. This helps on mac/linux, and almost on Windows. I know `skeema` claims `it cannot be compiled on Windows`, but it can, and works ok in simple mode. There should be some fix for the `cd` feature to work on windows, most of which are path handling.  It's not a fix for full windows support, so not worth a pull request~

* _ignore_ feature. **ignore** is a blacklist, and what we need here is a whitelist. I tried to use a complicated `everything but` regex expression (negative lookahead is not supported in regex package in golang). Maybe a `--only-schema` and `--only-table` support would be better.

I'm not familiar with `dep`, so I prefer not to update skeema vendor on my end, thanks  ;-

**patch for cd on windows**
```diff
diff --git a/fs/dir.go b/fs/dir.go
index ba72e05..b9e929a 100644
--- a/fs/dir.go
+++ b/fs/dir.go
@@ -7,6 +7,7 @@ import (
 	"os"
 	"path"
 	"path/filepath"
+	"runtime"
 	"sort"
 	"strconv"
 	"strings"
@@ -514,17 +515,20 @@ func ParentOptionFiles(dirPath string, baseConfig *mybase.Config) ([]*mybase.Fil
 	if err != nil {
 		return nil, err
 	}
-	cleaned = strings.TrimRight(cleaned, "/") // Prevent strings.Split from spitting out 2 blank strings for root dir
+	cleaned = strings.TrimRight(cleaned, string(os.PathSeparator)) // Prevent strings.Split from spitting out 2 blank strings for root dir
 
 	components := strings.Split(cleaned, string(os.PathSeparator))
+	if runtime.GOOS == "windows" && len(components[0]) == 2 && components[0][1] == ':' {
+		components[0] = components[0] + string(os.PathSeparator)
+	}
 	files := make([]*mybase.File, 0, len(components)-1)
 
 	// Examine parent dirs, going up one level at a time, stopping early if we
 	// hit either the user's home directory or a directory containing a .git subdir.
-	home := filepath.Clean(os.Getenv("HOME"))
+	home := util.GetUserHome()
 	var atRepoRoot bool
 	for n := len(components) - 1; n >= 0 && !atRepoRoot; n-- {
-		curPath := "/" + path.Join(components[0:n+1]...)
+		curPath := filepath.Join(components[0:n+1]...)
 		if curPath == home {
 			// We already read ~/.skeema as a global file
 			break
diff --git a/util/config.go b/util/config.go
index ccb3c86..a4ee273 100644
--- a/util/config.go
+++ b/util/config.go
@@ -4,9 +4,9 @@ import (
 	"errors"
 	"fmt"
 	"os"
-	"path"
 	"path/filepath"
 	"regexp"
+	"runtime"
 	"strings"
 	"syscall"
 
@@ -41,6 +41,20 @@ func AddGlobalOptions(cmd *mybase.Command) {
 	cmd.AddOption(mybase.BoolOption("debug", 0, false, "Enable debug logging"))
 }
 
+// GetUserHome returns the home directory of current user
+func GetUserHome() string {
+	home := os.Getenv("HOME")
+
+	if home == "" && runtime.GOOS == "windows" {
+		home = os.Getenv("HOMEDRIVE") + os.Getenv("HOMEPATH")
+		if home == "" {
+			home = os.Getenv("USERPROFILE")
+		}
+	}
+
+	return filepath.Clean(home)
+}
+
 // AddGlobalConfigFiles takes the mybase.Config generated from the CLI and adds
 // global option files as sources.
 func AddGlobalConfigFiles(cfg *mybase.Config) {
@@ -53,9 +67,9 @@ func AddGlobalConfigFiles(cfg *mybase.Config) {
 		globalFilePaths = append(globalFilePaths, "fake-etc/skeema", "fake-home/.my.cnf")
 	} else {
 		globalFilePaths = append(globalFilePaths, "/etc/skeema", "/usr/local/etc/skeema")
-		home := filepath.Clean(os.Getenv("HOME"))
+		home := GetUserHome()
 		if home != "" {
-			globalFilePaths = append(globalFilePaths, path.Join(home, ".my.cnf"), path.Join(home, ".skeema"))
+			globalFilePaths = append(globalFilePaths, filepath.Join(home, ".my.cnf"), filepath.Join(home, ".skeema"))
 		}
 	}
 

```

**Comment by evanelias** [comment]
Great, thanks! I've updated the vendored dep in skeema/skeema.

Regarding Windows support, I'm definitely open to pull requests there, even if just incremental improvements. However, I don't have a Windows machine to test on my end. btw, I've also heard the Linux build of Skeema works fine in Windows Subsystem for Linux (WSL). There were apparently some occasional line-ending annoyances (CRLF vs LF) but those are hopefully fixed now as of Skeema v1.2.1.

I'd consider `--only-table` but it depends on the use-case -- i.e. what's the motivation for only wanting to push certain tables. (The assumed workflow in Skeema is that the entire schema repo should represent the desired state of the database at any given time; if more granular changes are desired, you can always just make each git commit only affect one table...)

If the desire is to approve each change individually, perhaps an `--interactive` mode would be useful, displaying each change and then prompting whether to proceed.

Meanwhile not sure if `--only-schema` would be needed, since `cd`ing to the desired schema directory should basically do the same thing, if I understand the requirement correctly.

**Pull request merged**
